
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        rtInicial = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rtEmail = new javax.swing.JLabel();
        cxEmail = new javax.swing.JTextField();
        rtSenha = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        pfSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        barMenuPrinc = new javax.swing.JMenuBar();
        mnUsuario = new javax.swing.JMenu();
        itMnCadClient = new javax.swing.JMenuItem();
        itMnCadForn = new javax.swing.JMenuItem();
        mnProduto = new javax.swing.JMenu();
        itMnCadRef = new javax.swing.JMenuItem();
        itMnCadMed = new javax.swing.JMenuItem();
        itMnCadBeb = new javax.swing.JMenuItem();
        itMnCadMerc = new javax.swing.JMenuItem();
        mnPedido = new javax.swing.JMenu();
        itMnCadPed = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        rtInicial.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        rtInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtInicial.setText("Bem-vindo(a) ao AiLarica");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informe suas credenciais para fazer login");

        rtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtEmail.setText("E-mail:");

        cxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxEmailActionPerformed(evt);
            }
        });

        rtSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rtSenha.setText("Senha:");

        btEntrar.setBackground(new java.awt.Color(204, 204, 204));
        btEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Não tem uma conta?");

        btCadastro.setText("Cadastre-se");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        mnUsuario.setText("Usuario");

        itMnCadClient.setText("Cadastrar Cliente");
        itMnCadClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadClientActionPerformed(evt);
            }
        });
        mnUsuario.add(itMnCadClient);

        itMnCadForn.setText("Cadastrar Fornecedor");
        itMnCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFornActionPerformed(evt);
            }
        });
        mnUsuario.add(itMnCadForn);

        barMenuPrinc.add(mnUsuario);

        mnProduto.setText("Produto");

        itMnCadRef.setText("Cadastrar Refeicao");
        itMnCadRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadRefActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadRef);

        itMnCadMed.setText("Cadastrar Medicamento");
        itMnCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMedActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadMed);

        itMnCadBeb.setText("Cadastrar Bebida");
        itMnCadBeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadBebActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadBeb);

        itMnCadMerc.setText("Cadastrar Mercadoria");
        itMnCadMerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMercActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadMerc);

        barMenuPrinc.add(mnProduto);

        mnPedido.setText("Pedido");

        itMnCadPed.setText("Cadastrar Pedido");
        itMnCadPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadPedActionPerformed(evt);
            }
        });
        mnPedido.add(itMnCadPed);

        barMenuPrinc.add(mnPedido);

        setJMenuBar(barMenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rtInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadastro))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rtSenha)
                        .addComponent(rtEmail)
                        .addComponent(btEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cxEmail)
                        .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rtInicial)
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rtEmail)
                .addGap(4, 4, 4)
                .addComponent(cxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void itMnCadClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadClientActionPerformed
        FormCadCliente.getCadClient().setVisible(true);
    }//GEN-LAST:event_itMnCadClientActionPerformed

    private void itMnCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFornActionPerformed
        FormCadFornecedor.getCadFornecedor().setVisible(true);
    }//GEN-LAST:event_itMnCadFornActionPerformed

    private void itMnCadRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadRefActionPerformed
        //FormCadRefeicao.getCadRef().setVisible(true);
    }//GEN-LAST:event_itMnCadRefActionPerformed

    private void itMnCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMedActionPerformed
        //FormCadMedicamento.getCadProd().setVisible(true);
    }//GEN-LAST:event_itMnCadMedActionPerformed

    private void itMnCadBebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadBebActionPerformed
        //FormCadBebida.getCadProd().setVisible(true);
    }//GEN-LAST:event_itMnCadBebActionPerformed

    private void itMnCadMercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMercActionPerformed
       // FormCadMercadoria.getCadProd().setVisible(true);
    }//GEN-LAST:event_itMnCadMercActionPerformed

    private void itMnCadPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadPedActionPerformed
        FormCadPedido.getCadPed().setVisible(true);
    }//GEN-LAST:event_itMnCadPedActionPerformed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        String email = cxEmail.getText();
        String senha = new String(pfSenha.getPassword());

        int tipoUsuario = verificarUsuario(email, senha);

        switch (tipoUsuario) {
        // Leva para a página de cliente
            case 0:
                FormCatalogo.getCatalogo().setVisible(true);
                break;
        // Leva para a página de fornecedor
            case 1:
                
                break;
            default:
                JOptionPane.showMessageDialog(null, "Email e/ou senha incorretos", "Credenciais inválidas", JOptionPane.ERROR_MESSAGE);
                cxEmail.setText(""); 
                pfSenha.setText("");
                cxEmail.requestFocus();
                break;
        }
    }//GEN-LAST:event_btEntrarActionPerformed

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfSenhaActionPerformed

    private void cxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxEmailActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed

        Object[] options = { "Cliente", "Fornecedor" };

        int resposta = JOptionPane.showOptionDialog(
            null, 
            "Gostaria de se cadastrar como que tipo de usuário?",
            "Confirmação",
            JOptionPane.YES_NO_CANCEL_OPTION, 
            JOptionPane.QUESTION_MESSAGE,
            null, 
            options, 
            options[0]
        );

        // Tratando a resposta do usuário
        if (resposta == 0) {
            FormCadCliente.getCadClient().setVisible(true);
        } else if (resposta == 1) {
            FormCadFornecedor.getCadFornecedor().setVisible(true);
        }
    }//GEN-LAST:event_btCadastroActionPerformed
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saindo...", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    public int verificarUsuario(String email, String senhaDigitada) {
        ClienteDAO clienteDAO = new ClienteDAO();
        Cliente cliente = clienteDAO.consultarClientePorEmail(email);

        if (cliente != null && validarSenha(senhaDigitada, cliente.getSenha())) {
            return 0; // Cliente
        }

        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        Fornecedor fornecedor = fornecedorDAO.consultarFornecedorPorEmail(email);

        if (fornecedor != null && validarSenha(senhaDigitada, fornecedor.getSenha())) {
            return 1; // Fornecedor
        }

        return -1; // Usuário não encontrado ou senha incorreta
    }
    
    private boolean validarSenha(String senhaDigitada, String senhaCorreta) {
        return senhaDigitada.equals(senhaCorreta);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenuPrinc;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxEmail;
    private javax.swing.JMenuItem itMnCadBeb;
    private javax.swing.JMenuItem itMnCadClient;
    private javax.swing.JMenuItem itMnCadForn;
    private javax.swing.JMenuItem itMnCadMed;
    private javax.swing.JMenuItem itMnCadMerc;
    private javax.swing.JMenuItem itMnCadPed;
    private javax.swing.JMenuItem itMnCadRef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mnPedido;
    private javax.swing.JMenu mnProduto;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JLabel rtEmail;
    private javax.swing.JLabel rtInicial;
    private javax.swing.JLabel rtSenha;
    // End of variables declaration//GEN-END:variables
}
