// Nome: Abner do Nascimento Santos - RA: 2504154 
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormCadRefeicao extends javax.swing.JFrame {

    private Refeicao refeicao;
    private BDClasses gerRefeicao = BDClasses.getInstance();
    
    private static FormCadRefeicao cadRefUnico;
    
    private FormCadRefeicao() {
        initComponents();
    }
    
    //MÉTODO SINGLETON
    public static FormCadRefeicao getCadRef(){
        if(cadRefUnico == null){
            cadRefUnico = new FormCadRefeicao();
            System.out.println("\nCADREF NOVO");
        }
        else{
            System.out.println("\nCADREF VELHO");
        }
        return cadRefUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btExcluirProdId = new javax.swing.JButton();
        cxNome = new javax.swing.JTextField();
        rtId = new javax.swing.JLabel();
        rtPreco = new javax.swing.JLabel();
        cxPreco = new javax.swing.JTextField();
        rtQuant = new javax.swing.JLabel();
        cxQuant = new javax.swing.JTextField();
        rtDesc = new javax.swing.JLabel();
        cxDesc = new javax.swing.JTextField();
        cxId = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btCadProd = new javax.swing.JButton();
        btConsProdId = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btAltProdId = new javax.swing.JButton();
        rtNome = new javax.swing.JLabel();
        rtForn = new javax.swing.JLabel();
        rtTempo = new javax.swing.JLabel();
        rtIngred = new javax.swing.JLabel();
        rtAcomp = new javax.swing.JLabel();
        cxForn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cxTempo = new javax.swing.JTextField();
        cxAcomp = new javax.swing.JTextField();
        cxIngred = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btExcluirProdId.setText("Excluir por ID");
        btExcluirProdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirProdIdActionPerformed(evt);
            }
        });

        rtId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtId.setText("ID: ");

        rtPreco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtPreco.setText("Preço:");

        cxPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPrecoActionPerformed(evt);
            }
        });

        rtQuant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtQuant.setText("Quantidade:");

        rtDesc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtDesc.setText("Descrição:");

        cxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btCadProd.setText("Cadastrar");
        btCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadProdActionPerformed(evt);
            }
        });

        btConsProdId.setText("Consultar ID");
        btConsProdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsProdIdActionPerformed(evt);
            }
        });

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "PREÇO", "FORNECEDOR", "QUANT", "DESCRICAO", "TEMPO", "INGREDIENTES", "ACOMPANHAMENTO"
            }
        ));
        jScrollPane1.setViewportView(tblProd);
        if (tblProd.getColumnModel().getColumnCount() > 0) {
            tblProd.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblProd.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblProd.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblProd.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        btAltProdId.setText("Alterar pelo ID");
        btAltProdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltProdIdActionPerformed(evt);
            }
        });

        rtNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtNome.setText("Nome:");

        rtForn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtForn.setText("Fornecedor:");

        rtTempo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtTempo.setText("Tempo de Preparo:");

        rtIngred.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtIngred.setText("Ingredientes:");

        rtAcomp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtAcomp.setText("Acompanhamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtAcomp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxAcomp))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(163, 163, 163)
                                            .addComponent(rtNome)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxNome))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(rtForn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cxForn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtId)
                                    .addGap(12, 12, 12)
                                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btLimpar)
                                    .addGap(37, 37, 37)
                                    .addComponent(btSair))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtTempo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(rtIngred)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxIngred, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtQuant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rtDesc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btCadProd)
                .addGap(43, 43, 43)
                .addComponent(btConsProdId)
                .addGap(52, 52, 52)
                .addComponent(btAltProdId)
                .addGap(49, 49, 49)
                .addComponent(btExcluirProdId)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtId)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtForn)
                    .addComponent(cxForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtQuant)
                    .addComponent(cxQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtDesc)
                    .addComponent(cxDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTempo)
                    .addComponent(cxTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtIngred)
                    .addComponent(cxIngred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtAcomp)
                    .addComponent(cxAcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadProd)
                    .addComponent(btConsProdId)
                    .addComponent(btAltProdId)
                    .addComponent(btExcluirProdId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirProdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirProdIdActionPerformed
        excluir();
        listarTab();
    }//GEN-LAST:event_btExcluirProdIdActionPerformed

    private void cxPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPrecoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadProdActionPerformed
        cadastrar();
        listarTab();
    }//GEN-LAST:event_btCadProdActionPerformed

    private void btConsProdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsProdIdActionPerformed
        consultar();
    }//GEN-LAST:event_btConsProdIdActionPerformed

    private void btAltProdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltProdIdActionPerformed
        alterar();
        listarTab();
    }//GEN-LAST:event_btAltProdIdActionPerformed

    private void cxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdActionPerformed

    public void excluir(){
        refeicao = new Refeicao();
      
         try{
            refeicao.setIdProd(cxId.getText());
            
            refeicao = gerRefeicao.consProdId(refeicao);
         
            if(refeicao != null){
                
                cxId.setText(Integer.toString(refeicao.getIdProd()));
                cxNome.setText(refeicao.getNomeProd());
                
                int x = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o refeicao?", "Exclusão de refeicao", JOptionPane.YES_NO_CANCEL_OPTION);
                if(x == 0){
                    gerRefeicao.removeProdId(refeicao);
                    JOptionPane.showMessageDialog(null, "Refeicao removida com sucesso!", "Remoção de refeicao", 1);
                    limpar();
                }
            }
            else{
              JOptionPane.showMessageDialog(null, "Não existe refeicao com este ID!", "Refeicao inexistente", 0);
              cxId.setText("");
              cxId.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "O ID deve ser um inteiro!", "ERRO de ID", 0);
            cxId.setText("");
            cxId.requestFocus();
        } //fim catch

    
    }
    
    public void alterar(){
        refeicao = new Refeicao();
      
         try{
            refeicao.setIdProd(cxId.getText());
                
            refeicao = gerRefeicao.atualizaProdId(refeicao);
         
            if(refeicao != null){
                JOptionPane.showMessageDialog(null, "Refeicao atualizado!", "refeicao Atualizado", 1);
                limpar();
             }
            else{
              JOptionPane.showMessageDialog(null, "Não existe refeicao com este codigo!", "Refeicao inexistente", 0);
              cxId.setText("");
              cxId.requestFocus();
            }
        } 
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "O ID deve ser um inteiro!", "ERRO de ID", 0);
            cxId.setText("");
            cxId.requestFocus();
        } //fim catch
    }
    
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tblProd.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        for(Refeicao refeicao : gerRefeicao.getBdRef()){
            modelo.insertRow(posLin, new Object[]{refeicao.getIdProd(), refeicao.getNomeProd(), refeicao.getPreco(), refeicao.getFornecedor(), refeicao.getQuant(), refeicao.getDesc(), refeicao.getTempo(), refeicao.getIngred(), refeicao.getAcomp()});
            posLin++;
        }
    }
    
        public void consultar(){
        refeicao = new Refeicao();
      
         try{
            refeicao.setIdProd(cxId.getText());
                
            refeicao = gerRefeicao.consProdId(refeicao);
         
         if(refeicao != null){
            cxId.setText(Integer.toString(refeicao.getIdProd()));
            cxNome.setText(refeicao.getNomeProd());
            cxPreco.setText(Double.toString(refeicao.getPreco()));
            cxQuant.setText(Integer.toString(refeicao.getQuant()));
            cxDesc.setText(refeicao.getDesc());
            cxForn.setText(refeicao.getFornecedor());
            cxTempo.setText(Integer.toString(refeicao.getTempo()));
            cxIngred.setText(refeicao.getIngred());
            cxAcomp.setText(refeicao.getAcomp());
            JOptionPane.showMessageDialog(null, "Confira os dados da refeicao!", "Refeicao encontrada", 1);
            limpar();
         }
         else{
            JOptionPane.showMessageDialog(null, "Não existe refeicao com este codigo!", "Refeicao inexistente", 0);
            cxId.setText("");
            cxId.requestFocus();
         }
        } //fim try
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "O codigo deve ser um inteiro!", "ERRO de codigo", 0);
            cxId.setText("");
            cxId.requestFocus();
        } //fim catch
    }
    
    public void cadastrar(){
        refeicao = new Refeicao();
        try{
            refeicao.setIdProd(cxId.getText());
            refeicao.setNomeProd(cxNome.getText());
            refeicao.setPreco(cxPreco.getText());
            refeicao.setQuant(cxQuant.getText());
            refeicao.setDesc(cxDesc.getText());
            refeicao.setFornecedor(cxForn.getText()); //Não há como verificar se Fornecedor já foi cadastrado
            refeicao.setTempo(cxTempo.getText());
            refeicao.setIngred(cxIngred.getText());
            refeicao.setAcomp(cxAcomp.getText());
                 
         refeicao = gerRefeicao.cadProd(refeicao);
         
         if(refeicao != null){
            refeicao.impDados();
            limpar();
         }
         else{
            JOptionPane.showMessageDialog(null, "Já existe uma refeicao com este codigo!", "ERRO de ID", 0);
            cxId.setText("");
            cxId.requestFocus();
         }
        } 
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(null, "O ID deve ser um inteiro!", "ERRO de ID", 0);
            cxId.setText("");
            cxId.requestFocus();
        }
        catch (NumberException ne) {
            StackTraceElement[] stackTrace = ne.getStackTrace();
            if (stackTrace[0].getMethodName().equals("setQuant")) {
                JOptionPane.showMessageDialog(null, "A quantidade deve ser um inteiro!", "ERRO de Quantidade", 0);
                cxQuant.setText("");
                cxQuant.requestFocus();
            } else if (stackTrace[0].getMethodName().equals("setTempo")) {
                JOptionPane.showMessageDialog(null, "O tempo deve ser um inteiro!", "ERRO de inserção", 0);
                cxTempo.setText("");
                cxTempo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Erro desconhecido!", "ERRO", 0);
            }        
        } 
        catch (DecimalNumberException dne) {
            JOptionPane.showMessageDialog(null, "O preço deve ser um valor valido!", "ERRO de Preço", 0);
            cxPreco.setText("");
            cxPreco.requestFocus();
        }
        
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?","Confirmar Saída", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    public void limpar(){
        cxId.setText("");
        cxNome.setText("");
        cxPreco.setText("");
        cxQuant.setText("");
        cxDesc.setText("");
        cxForn.setText("");
        cxTempo.setText("");
        cxIngred.setText("");
        cxAcomp.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltProdId;
    private javax.swing.JButton btCadProd;
    private javax.swing.JButton btConsProdId;
    private javax.swing.JButton btExcluirProdId;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAcomp;
    private javax.swing.JTextField cxDesc;
    private javax.swing.JTextField cxForn;
    private javax.swing.JTextField cxId;
    private javax.swing.JTextField cxIngred;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPreco;
    private javax.swing.JTextField cxQuant;
    private javax.swing.JTextField cxTempo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel rtAcomp;
    private javax.swing.JLabel rtDesc;
    private javax.swing.JLabel rtForn;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtIngred;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtPreco;
    private javax.swing.JLabel rtQuant;
    private javax.swing.JLabel rtTempo;
    private javax.swing.JTable tblProd;
    // End of variables declaration//GEN-END:variables
}
