// Apache NetBeans IDE 22
// Nome: Abner do Nascimento Santos - RA: 2504154 

import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        rtInicial = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barMenuPrinc = new javax.swing.JMenuBar();
        mnUsuario = new javax.swing.JMenu();
        itMnCadClient = new javax.swing.JMenuItem();
        itMnCadForn = new javax.swing.JMenuItem();
        mnProduto = new javax.swing.JMenu();
        itMnCadRef = new javax.swing.JMenuItem();
        itMnCadMed = new javax.swing.JMenuItem();
        itMnCadBeb = new javax.swing.JMenuItem();
        itMnCadMerc = new javax.swing.JMenuItem();
        mnPedido = new javax.swing.JMenu();
        itMnCadPed = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        rtInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtInicial.setText("Sistema de Gerenciamento de Pedidos");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione no menu se deseja acessar um tipo de usuário, produto ou pedido.");

        mnUsuario.setText("Usuario");

        itMnCadClient.setText("Cadastrar Cliente");
        itMnCadClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadClientActionPerformed(evt);
            }
        });
        mnUsuario.add(itMnCadClient);

        itMnCadForn.setText("Cadastrar Fornecedor");
        itMnCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFornActionPerformed(evt);
            }
        });
        mnUsuario.add(itMnCadForn);

        barMenuPrinc.add(mnUsuario);

        mnProduto.setText("Produto");

        itMnCadRef.setText("Cadastrar Refeicao");
        itMnCadRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadRefActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadRef);

        itMnCadMed.setText("Cadastrar Medicamento");
        itMnCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMedActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadMed);

        itMnCadBeb.setText("Cadastrar Bebida");
        itMnCadBeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadBebActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadBeb);

        itMnCadMerc.setText("Cadastrar Mercadoria");
        itMnCadMerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMercActionPerformed(evt);
            }
        });
        mnProduto.add(itMnCadMerc);

        barMenuPrinc.add(mnProduto);

        mnPedido.setText("Pedido");

        itMnCadPed.setText("Cadastrar Pedido");
        itMnCadPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadPedActionPerformed(evt);
            }
        });
        mnPedido.add(itMnCadPed);

        barMenuPrinc.add(mnPedido);

        setJMenuBar(barMenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rtInicial)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(rtInicial)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void itMnCadClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadClientActionPerformed
        FormCadCliente.getCadClient().setVisible(true);
    }//GEN-LAST:event_itMnCadClientActionPerformed

    private void itMnCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFornActionPerformed
        FormCadFornecedor.getCadFornecedor().setVisible(true);
    }//GEN-LAST:event_itMnCadFornActionPerformed

    private void itMnCadRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadRefActionPerformed
        FormCadRefeicao.getCadRef().setVisible(true);
    }//GEN-LAST:event_itMnCadRefActionPerformed

    private void itMnCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMedActionPerformed
        FormCadMedicamento.getCadProd().setVisible(true);
    }//GEN-LAST:event_itMnCadMedActionPerformed

    private void itMnCadBebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadBebActionPerformed
        FormCadBebida.getCadProd().setVisible(true);
    }//GEN-LAST:event_itMnCadBebActionPerformed

    private void itMnCadMercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMercActionPerformed
        FormCadMercadoria.getCadProd().setVisible(true);
    }//GEN-LAST:event_itMnCadMercActionPerformed

    private void itMnCadPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadPedActionPerformed
        FormCadPedido.getCadPed().setVisible(true);
    }//GEN-LAST:event_itMnCadPedActionPerformed
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja sair?", "Saindo...", JOptionPane.YES_NO_CANCEL_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenuPrinc;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem itMnCadBeb;
    private javax.swing.JMenuItem itMnCadClient;
    private javax.swing.JMenuItem itMnCadForn;
    private javax.swing.JMenuItem itMnCadMed;
    private javax.swing.JMenuItem itMnCadMerc;
    private javax.swing.JMenuItem itMnCadPed;
    private javax.swing.JMenuItem itMnCadRef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu mnPedido;
    private javax.swing.JMenu mnProduto;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JLabel rtInicial;
    // End of variables declaration//GEN-END:variables
}
